### ISSUE TITLE
Is the project fully open source?

### ISSUE THREAD

**Issue by ZiadJ** [syalanurag1991/OpenCVForUnity#1]
I mean are there any bits in the code that rely on any propriatory or closed DLLs?

**Comment by syalanurag1991** [comment]
Hey, sorry for the late reply. Nope there are no such proprietary libraries. It's only OpenCV and Kinect SDK which is pretty much open source.

**Comment by ZiadJ** [comment]
Thank for the info. It would help if we could have a list of closed sourced dependencies still.
